apiVersion: v1
kind: ConfigMap
metadata:
  name: be-config
data:
  DB_HOST: mysql-0.mysql-hl.default.svc.cluster.local
  DB_PORT: "3306"
  DB_DATABASE: user-feedback-app
  DB_USERNAME: john
  DB_CONNECTION: mysql

  APP_NAME: HTXH
  APP_ENV: production
  APP_DEBUG: "true"
  APP_URL: http://myapp.local
  
  SESSION_DRIVER: database
  CACHE_STORE: database
  QUEUE_CONNECTION: database
  
  LOG_CHANNEL: stack
  LOG_LEVEL: debug